ImageLink = {
    "엔비디아": "https://thumb.tossinvest.com/image/resized/256x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NAS00208X-E0.png",
    "테슬라" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NAS006XY7-E0.png",
    
    "애플" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NAS000C7F-E0.png",
    "마이크로소프트" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NAS000Q07-E0.png",
    "알파벳C" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NASWFJYTJ-R0.png",
    "알파벳A" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NASWFJYTJ-R0.png",
    "아마존" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NAS001MF1-E0.png",
    "메타" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-MVRS.png",
    "버크셔 해서웨이 B" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS000CS1-E0.png",
    "버크셔 해서웨이 A" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS000CS1-E0.png",
    "TSMC(ADR)" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS001Y70-E0.png%3F20240424",
    "일라이 릴리" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS000P56-E0.png",
    "브로드컴" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NAS0JCLYY-E0.png",
    "테슬라" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NAS006XY7-E0.png",
    "제이피모건 체이스" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS0035K2-E0.png%3F20240521",
    "월마트" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS000YMS-E0.png",
    "유나이티드헬스 그룹" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS000Y3J-E0.png",
    "엑슨 모빌" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS002Q0G-E0.png",
    "비자" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS05MDRV-E0.png",
    "노보노디스크(ADR)" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NVO.png",
    "마스터카드" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS0038M5-E0.png",
    "P&G" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS000TRY-E0.png",
    "코스트코" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NAS000F9X-E0.png",
    "존슨 앤 존슨" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS000NB6-E0.png",
    "오라클" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS000SY8-E0.png",
    "ASML 홀딩(ADR)" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NAS000CBQ-E0.png",
    "홈 디포" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS000LR9-E0.png",
    "애브비" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS00DYYX-E0.png",
    "뱅크오브아메리카" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS000R3K-E0.png",
    "코카콜라" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS000DWY-E0.png",
    "넷플릭스" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NAS002X9M-E0.png",
    "AT&T 일반채권(2069-01-08 5.625%)" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fassets%2Ficon%2Fsecurities%2Ficn-default.png",
    "AT&T" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS069J8N-E0.png",
    "머크" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS000PQC-E0.png",
    "스미토모 미쓰이 파이낸셜 그룹(ADR)" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS05H7ST-E0.png",
    "셰브론" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS000DP6-E0.png",
    "아스트라제네카(ADR)" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-AZN.png",
    "세일즈포스" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS0058W5-E0.png",
    "SAP(ADR)" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS05HDZK-E0.png",
    "AMD" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NAS000BK7-E0.png",
    "어도비" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NAS000BJT-E0.png",
    "토요타 모터(ADR)" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-TM.png",
    "펩시코" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NAS000T99-E0.png%3F20240520",
    "노바티스(ADR)" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NVS.png",
    "써모 피셔 사이언티픽" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS06LJVN-E0.png",
    "T 모바일" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NAS0D4BBG-E0.png",
    "쉘(ADR)" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-002960.png",
    "린데" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NAS0VR5Y5-E0.png",
    "판둬둬(ADR)" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-PDD.png",
    "액션츄어" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS00C5YS-E0.png",
    "맥도날드" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS000PLS-E0.png",
    "알리바바(ADR)" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS06ZPRF-E0.png",
    "웰스파고" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS000RGR-E0.png",
    "시스코 시스템즈" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NAS000DS6-E0.png",
    "다나허" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS000FHS-E0.png",
    "애보트 래버러토리스" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS000BG2-E0.png",
    "퀄컴" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NAS000V67-E0.png",
    "인튜이트" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NAS0011HX-E0.png",
    "GE 에어로스페이스" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS000KYG-E0.png",
    "필립 모리스 인터내셔널" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-PM.png",
    "텍사스 인스트루먼츠" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NAS000XNY-E0.png",
    "아메리칸 익스프레스" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS000BY7-E0.png",
    "IBM" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS000N1N-E0.png",
    "암젠" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NAS000C35-E0.png",
    "어플라이드 머티리얼즈" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NAS000C7R-E0.png",
    "모건스탠리" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS0013TZ-E0.png",
    "서비스나우" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS008L5S-E0.png",
    "버라이즌" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS000CQ8-E0.png",
    "인튜이티브 서지컬" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NAS0021ZC-E0.png",
    "캐터필러" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS000DFY-E0.png",
    "넥스트에라 에너지" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS000KQ5-E0.png",
    "디즈니" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS000HLG-E0.png",
    "블랙스톤" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS06T26D-E0.png",
    "화이자" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS000TBT-E0.png",
    "골드만삭스" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS002615-E0.png",
    "HSBC(ADR)" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS002J95-E0.png",
    "로열 뱅크 오브 캐나다" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-RY.png",
    "토탈에너지스(ADR)" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS002KX6-E0.png",
    "RTX" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-RTX.png%3F20230705",
    "컴캐스트" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NAS05LL2F-E0.png",
    "우버" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS0B49NF-E0.png",
    "S&P 글로벌" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS000PLZ-E0.png",
    "유니레버(ADR)" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-UL.png",
    "HDFC 뱅크(ADR)" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS003L7K-E0.png",
    "유니온 퍼시픽" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS000Y1Z-E0.png",
    "프로그레시브" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS000TSD-E0.png",
    "사노피(ADR)" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NAS005M9Z-E0.png",
    "허니웰 인터내셔널" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NAS002Q2X-E0.png",
    "코노코필립스" : "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS003GNF-E0.png",
    "TJX": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS000XRR-E0.png",
    "블랙록": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS002HJD-E0.png",
    "스트라이커": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-SYK.png",
    "리제네론 파마슈티컬스": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-REGN.png",
    "ARM 홀딩스(ADR)": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NAS0X9K7C-E0.png%3F20230918",
    "엘리번스 헬스": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS060W5N-E0.png",
    "버텍스 파마슈티컬": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NAS000YJB-E0.png",
    "미쓰비시 UFJ 파이낸셜(ADR)": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-MUFG.png",
    "부킹 홀딩스": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NAS0029GL-E0.png",
    "이튼": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-ETN.png",
    "찰스 슈왑": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS000VSF-E0.png",
    "나이키": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS000RBW-E0.png",
    "보스턴 사이언티픽": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-BSX.png",
    "프로로지스": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS0BTZL3-E0.png",
    "씨티그룹": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS0027L0-E0.png",
    "처브": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-CB.png",
    "팰로 앨토 네트웍스": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NAS0078TM-E0.png",
    "유나이티드 파셀 서비스": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS000Y4G-E0.png",
    "마시 앤 매클래넌": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-MMC.png",
    "아리스타 네트웍스": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-ANET.png",
    "램 리서치": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NAS000NYZ-E0.png",
    "오토매틱 데이터 프로세싱": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-ADP.png",
    "아메리칸 타워": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS0023JS-E0.png",
    "아날로그 디바이스": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-ADI.png",
    "안호이저부시 인베브(ADR)": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-BUD.png",
    "마이크론 테크놀로지": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NAS000PZY-E0.png",
    "메드트로닉": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS0DRH2W-E0.png",
    "소니(ADR)": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS001CJR-E0.png",
    "KLA": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NAS001NWQ-E0.png",
    "보잉": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS000CYC-E0.png",
    "KKR & CO": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-KKR.png%3F20230704",
    "토론토 도미니언 뱅크": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-TD.png",
    "UBS 그룹": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-UBS.png",
    "ICICI 뱅크(ADR)": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS002T0H-E0.png",
    "서던": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-SO.png",
    "메르카도리브레": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-MELI.png",
    "브리스톨 마이어스 스큅": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS000D1R-E0.png",
    "디어": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS000FMM-E0.png",
    "HCA 헬스케어": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-HCA.png",
    "파이서브": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS000KJ3-E0.png",
    "몬덜리즈 인터내셔널": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NAS002RNG-E0.png",
    "BP(ADR)": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-BP.png",
    "시그나 그룹": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS0JF71F-E0.png",
    "페트로브라스(ADR)": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-PBR.png",
    "페트로브라스 우선주(ADR)": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-PBR.png",
    "길리어드 사이언스": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NAS000L1R-E0.png",
    "듀크 에너지": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS06F9DV-E0.png",
    "인터컨티넨탈 익스체인지": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS0D819X-E0.png",
    "인포시스(ADR)": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS002C0D-E0.png",
    "쇼피파이": "https://thumb.tossinvest.com/image/resized/32x0/https%3A%2F%2Fstatic.toss.im%2Fpng-icons%2Fsecurities%2Ficn-sec-fill-NYS0958JJ-E0.png",

}
#"" : "",
#"" : "",
#"" : "",
#"" : "",
#"" : "",
#"" : "",
#"" : "",
#"" : "",
#"" : "",
#"" : "",
